spring:
  datasource:
    url: jdbc:mysql://10.233.166.39:33306/mall_tiny?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: XZyd12#$
    initialization-mode: always
    sql-script-encoding: utf-8
    schema: classpath:schema.sql
    data: classpath:data.sql

logging:
  level:
    root: info
    com.macro.mall: debug
